### ISSUE TITLE
Use without composer?

### ISSUE THREAD

**Issue by drewbaker** [qferr/mjml-php#1]
I’d like to have WordPress generate my MJML templates with data from the CMS. Is it possible to use this without composer?

**Comment by qferr** [comment]
Yes you should download the package from the last tag. But you have to load the classes  `\Qferrer\Mjml\Renderer\*` with your own autoload.

**Comment by drewbaker** [comment]
Thanks! Not sure I understand the autoload part or how to install MJML onto a WordPress optimized host (WP-Engine or Flywheel). But I’ll play around with it and see what I can come up with. Any tips would be appreciated.

**Comment by qferr** [comment]
Sorry I've never used Wordpress, so I don't know how to install the package onto a Wordpress but if you post an example of your implementation, it will be a pleasure to help you.

**Comment by drewbaker** [comment]
Thanks @qferr. Well WordPress is just PHP based, but has no composer because it's really accessed via SFTP running on a managed server normally (no SSH access etc).

SendGrid has a packaged ZIP available for example: https://github.com/sendgrid/sendgrid-php#alternative-install-package-from-zip

Anyway, here is how I planned on using it. 

In this file: https://github.com/funkhaus/fuxt-backend/blob/master/functions/wp-functions.php

I'd have a function that is called by an AJAX request from my admin panel in WordPress:

```
    require_once 'vendor/autoload.php';

    function send_email() {

          // Build MJML template
          $renderer = new \Qferrer\Mjml\Renderer\BinaryRenderer(__DIR__ . '/node_modules/.bin/mjml');

          $html = $renderer->render('
              <mjml>
                  <mj-body>
                      <mj-section>
                          <mj-column>
                              <mj-text>Hello world</mj-text>
                          </mj-column>
                      </mj-section>
                  </mj-body>
              </mjml>
          ');

          // Send it using the SendGrid SDK
          //send_grid_send_email($to, $html)
    }
```

So I just need a way of putting all the files onto the server. Can I just upload `vendor` or or does something need to be compiled to pull in dependencies etc?

**Comment by qferr** [comment]
Hello @drewbaker, you have to upload all the files to your project directory on your server. You may need to change the autoload path depending on the location of the vendor directory: `require_once $projectDir . '/vendor/autoload.php';`.

Don't forget to change the path of the MJML binary. (depending on the location of the node_modules directory).

Keep me informed.

**Comment by qferr** [comment]
No more news, I'm closing the issue.

**Comment by drewbaker** [comment]
I ended up using `handlebars-php` and imported it like this:

```
// Load Handlebars PHP. See: https://github.com/salesforce/handlebars-php
require 'vendor/handlebars-php/src/Handlebars/Autoloader.php';
Handlebars\Autoloader::register();
use Handlebars\Handlebars;
use Handlebars\Loader\FilesystemLoader;
```
