### ISSUE TITLE
How to run in local windows environment?

### ISSUE THREAD

**Issue by jayhybrid** [qferr/mjml-php#2]
I am a novice programmer and I am trying to get this to work. Is there a way to disable this SSL check or whatever is going on for my local environment?

```
Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in [...]\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 201
```

**Comment by qferr** [comment]
Hi @jayhybrid. Did you check out the issue on https://github.com/guzzle/guzzle/issues/1935 ? There are some good feedback.

**Comment by jayhybrid** [comment]
Thanks a bunch! This helped me.

For anybody coming here with the same problem, this is the comment (https://github.com/guzzle/guzzle/issues/1935#issuecomment-371756738) that did the trick for me.

> Download the latest cacert.pem from https://curl.haxx.se/ca/cacert.pem
> Add the following line to php.ini:
> curl.cainfo="/path/to/downloaded/cacert.pem"
