### ISSUE TITLE
Can't make the BinaryRenderer working.

### ISSUE THREAD

**Issue by sukei** [qferr/mjml-php#23]
Hello,

I'm trying to compile template using the `Qferrer\Mjml\Renderer\BinaryRenderer` but I can't make it works and really don't know why. Here is my current setup: `"mjml": "^4.13.0"`, `"qferr/mjml-php": "^2.0"` and node `v18.6.0`. 

A `Qferrer\Mjml\Process\ProcessException` is thrown without any exception message (empty string). I tried something different just to validate the behavior of the MJML binary and it works flawlessly:

```
node_modules/.bin/mjml -i -s --config.validationLevel --config.minify < <(cat template.mjml)
```

On the other side, the `Qferrer\Mjml\Renderer\ApiRenderer` works fine.

**Comment by qferr** [comment]
I ran unit tests and a PHP test file with the example from the README.md, I can't reproduce the problem. Did you try to run a PHP file test with the example?

**Comment by sukei** [comment]
Just did the same and it runs too. I will try to do the same in a fresh Symfony project to check if the framework or the SymfonyCLI is the cause.

**Comment by sukei** [comment]
Just build a new Sf Project served with `php -S` and with the `Symfony CLI` and everything works fine. I really don't know what is happening on the other project since the dependencies are the same. Anyway, it doesn't seems to be the library fault. Sorry for this @qferr.

**Comment by sukei** [comment]
For posterity, I just restarted my symfony proxy+server and it fixed the issue. I think that the `stdin` / `stdout` / `stderr` was poluted by it.

**Comment by qferr** [comment]
No worries. Happy to know it works! Thank you for using and supporting this library. Cheers.

**Comment by qferr** [comment]
@sboerrigter can you take a look at this issue?

**Comment by sboerrigter** [comment]
I am on vacation. I will look at it later. Sorry.
