### ISSUE TITLE
Stop using Symfony and Guzzle dependencies

### ISSUE THREAD

**Issue by qferr** [qferr/mjml-php#9]
Since this is a simple PHP library, I plan to remove the Symfony and Guzzle dependencies to avoid loading a lot of unnecessary files into the vendor. It must be a simple library, so I'll replace Guzzle using PHP's curl functions and Symfony Process using PHP's exec function. This way, I will no longer have to keep updating the version of these libraries and the project will be lighter.

**Comment by qferr** [comment]
Hi @mipapo. It's done. I hope you enjoy the new 2.0 version of this library.

**Comment by mipapo** [comment]
Awesome  - Thanks @qferr for the update - Have a nice sunday!
